export default ({
  naver: {
    frontend: ['프론트엔드', 'FE'],
    backend: ['백엔드'],
    dataScience: ['Bigdata'],
    ai: ['Machine Learning'],
    android: ['Android'],
    ios: ['iOS'],
  },
  lineplus: {
    frontend: ['Front-end'],
    backend: ['Server-dev'],
    devOps: ['Cloud/Infra'],
    dataScience: ['Data'],
    ai: ['AI/ML'],
    blockchain: ['Blockchain'],
    android: ['Android'],
    ios: ['iOS'],
    game: ['Game'],
    test: ['QA'],
    pm: ['Management/Operation'],
    security: ['Security'],
  },
  kakao: {
    frontend: ['Web_front'],
    backend: ['Server', 'Hadoop_eco_system'],
    devOps: ['Cloud'],
    dataScience: ['Statistics_Analysis'],
    ai: ['Algorithm_ML', 'Algorithm_Ranking', 'NLP', 'NLP_Linguist', ],
    blockchain: [],
    android: ['Android'],
    ios: ['iOS'],
    system: ['System'],
    test: ['QA'],
    security: ['Security'],
  },
  zeplSeoul: {
    frontend: ['Frontend'],
    backend: ['Backend'],
    devOps: ['DevOps'],
    test: ['QA'],
  },
  rainst: {
    frontend: ['Front-end'],
    backend: ['Server', 'SRE'],
    devOps: ['Infra', 'Productivity'],
    dataScience: ['Data'],
    ai: ['Machine'],
    android: ['Android'],
    ios: ['iOS'],
    test: ['QA', 'Test'],
    security: ['Security'],
    growthHacker: ['Growth'],
  },
  skelterlabs: {
    frontend: ['UX Engineer', 'Product Engineer'],
    backend: ['Software Engineer', 'Product Engineer', 'Site Reliability Engineer'],
    android: ['Product Engineer'],
    ios: ['Product Engineer'],
  },
});
